// <auto-generated />
using System;
using Irrigation.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IrigationSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200229172856_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Irrigation.Entities.HumidityStat", b =>
                {
                    b.Property<int>("HumidityStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastRead")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HumidityStatId");

                    b.HasIndex("PlantId");

                    b.ToTable("HumidityStats");
                });

            modelBuilder.Entity("Irrigation.Entities.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Species")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("SubSpecies")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Irrigation.Entities.PlantSensorMapping", b =>
                {
                    b.Property<int>("PlantSensorMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantSensorMappingId");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("PlantSensorMappings");
                });

            modelBuilder.Entity("Irrigation.Entities.PlantSettings", b =>
                {
                    b.Property<int>("PlantSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("HumidityThresholdHigh")
                        .HasColumnType("REAL");

                    b.Property<float>("HumidityThresholdLow")
                        .HasColumnType("REAL");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlantSettingsId");

                    b.HasIndex("PlantId")
                        .IsUnique();

                    b.ToTable("PlantSettings");
                });

            modelBuilder.Entity("Irrigation.Entities.Settings", b =>
                {
                    b.Property<int>("SettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WaterTime")
                        .HasColumnType("TEXT");

                    b.HasKey("SettingsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Irrigation.Entities.SunStat", b =>
                {
                    b.Property<int>("SunStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Irradiance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LastRead")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SunStatId");

                    b.HasIndex("PlantId");

                    b.ToTable("SunStats");
                });

            modelBuilder.Entity("Irrigation.Entities.TempatureStat", b =>
                {
                    b.Property<int>("TempatureStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastRead")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Tempature")
                        .HasColumnType("REAL");

                    b.HasKey("TempatureStatId");

                    b.HasIndex("PlantId");

                    b.ToTable("TempatureStats");
                });

            modelBuilder.Entity("Irrigation.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Irrigation.Entities.WaterLog", b =>
                {
                    b.Property<int>("WaterLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WaterDate")
                        .HasColumnType("TEXT");

                    b.HasKey("WaterLogId");

                    b.HasIndex("PlantId");

                    b.ToTable("WarterLogs");
                });

            modelBuilder.Entity("Irrigation.Entities.HumidityStat", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithMany("HumidityStats")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.Plant", b =>
                {
                    b.HasOne("Irrigation.Entities.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.PlantSensorMapping", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithOne("PlantSensorMapping")
                        .HasForeignKey("Irrigation.Entities.PlantSensorMapping", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.PlantSettings", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithOne("PlantSettings")
                        .HasForeignKey("Irrigation.Entities.PlantSettings", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.Settings", b =>
                {
                    b.HasOne("Irrigation.Entities.User", null)
                        .WithOne("Settings")
                        .HasForeignKey("Irrigation.Entities.Settings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.SunStat", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithMany("SunStats")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.TempatureStat", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithMany("TempatureStats")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Irrigation.Entities.WaterLog", b =>
                {
                    b.HasOne("Irrigation.Entities.Plant", "Plant")
                        .WithMany("WaterLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
