version: '3'
services:
    ui:
        container_name: irigation-system-ui
        build: ./ui
        command: sh -c 'npm run serve'
        volumes: 
            - './ui:/app'
            - '/app/node_modules'
        ports:
            - '8080:8080'
        working_dir: /app
    api:
        container_name: irigation-system-api
        build: ./api
        command: $CMD
        ports:
            - '5000:5000'
        working_dir: /app
        volumes:
            - './api:/app'
