version: '3'
services:
    ui:
        container_name: irigation-system-ui
        build: ./ui
        command: sh -c "npm run serve"
        volumes: 
            - './ui:/app'
            - '/app/node_modules'
        ports:
            - '8081:8080'
        working_dir: /app
        
